apiVersion: v1
kind: Service
metadata:
  namespace: task-appns
  name: task-app-task-1
spec:
  selector:
    app: task-app-task-1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort